server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: item-service

          # /item-service로 시작하는 url요청이 들어올 경우
          predicates:
            - Path=/item-service/**

          # filters에 StripPrefix=1은 천번째 접두어 제거
          filters:
            - StripPrefix=1

          # lb:aplication.name (eureka에 등록된 서비스명)
          # uri: http:localhost:8081로 선언하면 로드밸런싱이 아니라 8081로 직접 연결
          uri: lb://item-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

